{
 "title": "Dashboards Desafio DevOps",
 "description": "Dashboards do desafio técnico para a Idus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate by HTTP Status Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"prometheus.scrape.simulator_metrics\",status=\"500\"}[1m]))\n/\nsum(rate(http_requests_total{job=\"prometheus.scrape.simulator_metrics\"}[1m]))\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by endpoint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (\n  rate(http_requests_total{job=\"prometheus.scrape.simulator_metrics\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_milliseconds_sum[1m])\n/\nrate(http_request_duration_milliseconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_request_duration_milliseconds_bucket[1m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"prometheus.scrape.simulator_metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}